
const testDatasetExact = [
    // Greeting examples
    { text: 'hello', expectedIntent: 'greeting' },
    { text: 'hi', expectedIntent: 'greeting' },
    { text: 'hey', expectedIntent: 'greeting' },
    { text: 'good morning', expectedIntent: 'greeting' },
    { text: 'good afternoon', expectedIntent: 'greeting' },
    { text: 'good evening', expectedIntent: 'greeting' },
    { text: 'hiya', expectedIntent: 'greeting' },
    { text: 'hello my name is', expectedIntent: 'greeting' },
    { text: 'sup', expectedIntent: 'greeting' },
    { text: 'greetings', expectedIntent: 'greeting' },
    { text: 'hi there', expectedIntent: 'greeting' },
    { text: 'hey there', expectedIntent: 'greeting' },
    { text: 'hello there', expectedIntent: 'greeting' },
    { text: 'yo', expectedIntent: 'greeting' },
    { text: 'hello im Josh', expectedIntent: 'greeting' },

    // Farewell examples
    { text: 'bye', expectedIntent: 'farewell' },
    { text: 'goodbye', expectedIntent: 'farewell' },
    { text: 'see you later', expectedIntent: 'farewell' },
    { text: 'catch you later', expectedIntent: 'farewell' },
    { text: 'cheerio', expectedIntent: 'farewell' },
    { text: 'bye then', expectedIntent: 'farewell' },
    { text: 'im off', expectedIntent: 'farewell' },
    { text: 'bye bye', expectedIntent: 'farewell' },
    { text: 'see ya', expectedIntent: 'farewell' },
    { text: 'later', expectedIntent: 'farewell' },
    { text: 'talk to you later', expectedIntent: 'farewell' },
    { text: 'farewell', expectedIntent: 'farewell' },
    { text: 'take care', expectedIntent: 'farewell' },
    { text: 'see you', expectedIntent: 'farewell' },
    { text: 'catch you', expectedIntent: 'farewell' },

    // Name examples
    { text: 'who are you', expectedIntent: 'name' },
    { text: 'what is your name', expectedIntent: 'name' },
    { text: 'what are you called', expectedIntent: 'name' },
    { text: 'do you have a name', expectedIntent: 'name' },
    { text: 'may I ask your name', expectedIntent: 'name' },
    { text: 'tell me your name', expectedIntent: 'name' },
    { text: 'what should I call you', expectedIntent: 'name' },
    { text: 'how should I address you', expectedIntent: 'name' },
    { text: 'your name', expectedIntent: 'name' },
    { text: 'who am I talking to', expectedIntent: 'name' },
    { text: 'what do people call you', expectedIntent: 'name' },
    { text: 'name', expectedIntent: 'name' },

    // Age examples
    { text: 'how old are you', expectedIntent: 'age' },
    { text: 'what is your age', expectedIntent: 'age' },
    { text: 'can you tell me your age', expectedIntent: 'age' },
    { text: 'how many years old are you', expectedIntent: 'age' },
    { text: 'tell me your age', expectedIntent: 'age' },
    { text: 'I was wondering how old you are', expectedIntent: 'age' },
    { text: 'your age', expectedIntent: 'age' },
    { text: 'how old', expectedIntent: 'age' },

    // Birthplace examples
    { text: 'where were you born', expectedIntent: 'birthplace' },
    { text: 'what town were you born in', expectedIntent: 'birthplace' },
    { text: 'where did you grow up', expectedIntent: 'birthplace' },
    { text: 'where is your hometown', expectedIntent: 'birthplace' },
    { text: 'where are you from', expectedIntent: 'birthplace' },
    { text: 'what city were you born in', expectedIntent: 'birthplace' },
    { text: 'may I ask where you were born', expectedIntent: 'birthplace' },
    { text: 'your city', expectedIntent: 'birthplace' }
];



const testDatasetFuzzy = [
    // Greeting examples
    { text: 'helo', expectedIntent: 'greeting' },
    { text: 'hi theree', expectedIntent: 'greeting' },
    { text: 'good mornin', expectedIntent: 'greeting' },
    { text: 'good afteroon', expectedIntent: 'greeting' },
    { text: 'gud evening', expectedIntent: 'greeting' },
    { text: 'hiyaa', expectedIntent: 'greeting' },
    { text: 'hello im', expectedIntent: 'greeting' },
    { text: 'sup?', expectedIntent: 'greeting' },
    { text: 'greetngs', expectedIntent: 'greeting' },
    { text: 'hey thr', expectedIntent: 'greeting' },
    { text: 'yo!', expectedIntent: 'greeting' },
    { text: 'hi thare', expectedIntent: 'greeting' },
    { text: 'helloo there', expectedIntent: 'greeting' },
    { text: 'hey theree', expectedIntent: 'greeting' },
    { text: 'hi im Josh', expectedIntent: 'greeting' },

    // Farewell examples
    { text: 'byee', expectedIntent: 'farewell' },
    { text: 'goodby', expectedIntent: 'farewell' },
    { text: 'se u later', expectedIntent: 'farewell' },
    { text: 'catc hu later', expectedIntent: 'farewell' },
    { text: 'cheerioo', expectedIntent: 'farewell' },
    { text: 'bye thenn', expectedIntent: 'farewell' },
    { text: 'im offf', expectedIntent: 'farewell' },
    { text: 'by bye', expectedIntent: 'farewell' },
    { text: 'see yaa', expectedIntent: 'farewell' },
    { text: 'latr', expectedIntent: 'farewell' },
    { text: 'tak to u later', expectedIntent: 'farewell' },
    { text: 'farewel', expectedIntent: 'farewell' },
    { text: 'take caree', expectedIntent: 'farewell' },
    { text: 'seee u', expectedIntent: 'farewell' },
    { text: 'catch u', expectedIntent: 'farewell' },

    // Name examples
    { text: 'who r you', expectedIntent: 'name' },
    { text: 'wat is your name', expectedIntent: 'name' },
    { text: 'what u called', expectedIntent: 'name' },
    { text: 'do u have name', expectedIntent: 'name' },
    { text: 'may i ask nsme', expectedIntent: 'name' },
    { text: 'tell me ur name', expectedIntent: 'name' },
    { text: 'what shud i call u', expectedIntent: 'name' },
    { text: 'how should i adress u', expectedIntent: 'name' },
    { text: 'ur name', expectedIntent: 'name' },
    { text: 'who amm i talking too', expectedIntent: 'name' },
    { text: 'wat do ppl call you', expectedIntent: 'name' },
    { text: 'nam', expectedIntent: 'name' },

    // Age examples
    { text: 'how old r u', expectedIntent: 'age' },
    { text: 'wat is ur age', expectedIntent: 'age' },
    { text: 'can u tel me age', expectedIntent: 'age' },
    { text: 'how many years old r u', expectedIntent: 'age' },
    { text: 'tell me ur age', expectedIntent: 'age' },
    { text: 'i wonder how old r u', expectedIntent: 'age' },
    { text: 'ur age', expectedIntent: 'age' },
    { text: 'how old', expectedIntent: 'age' },

    // Birthplace examples
    { text: 'were u born', expectedIntent: 'birthplace' },
    { text: 'what town u born in', expectedIntent: 'birthplace' },
    { text: 'wher did u grow', expectedIntent: 'birthplace' },
    { text: 'where is ur homtown', expectedIntent: 'birthplace' },
    { text: 'where r u from', expectedIntent: 'birthplace' },
    { text: 'wat city were u born', expectedIntent: 'birthplace' },
    { text: 'may i ask u birthplace', expectedIntent: 'birthplace' },
    { text: 'ur city', expectedIntent: 'birthplace' }
];

const testDatasetBoundary = [
    // Greeting examples
    { text: 'hello friend', expectedIntent: 'greeting' },
    { text: 'hi there buddy', expectedIntent: 'greeting' },
    { text: 'hey you', expectedIntent: 'greeting' },
    { text: 'good morning everyone', expectedIntent: 'greeting' },
    { text: 'good afternoon all', expectedIntent: 'greeting' },
    { text: 'good evening to you', expectedIntent: 'greeting' },
    { text: 'hello im here', expectedIntent: 'greeting' },
    { text: 'hiya everyone', expectedIntent: 'greeting' },
    { text: 'yo my friend', expectedIntent: 'greeting' },
    { text: 'greetings folks', expectedIntent: 'greeting' },
    { text: 'hi there everyone', expectedIntent: 'greeting' },
    { text: 'hey there friend', expectedIntent: 'greeting' },
    { text: 'hello there my friend', expectedIntent: 'greeting' },
    { text: 'sup buddy', expectedIntent: 'greeting' },
    { text: 'hello there stranger', expectedIntent: 'greeting' },

    // Farewell examples
    { text: 'see you later my friend', expectedIntent: 'farewell' },
    { text: 'catch you later buddy', expectedIntent: 'farewell' },
    { text: 'bye everyone', expectedIntent: 'farewell' },
    { text: 'goodbye for now', expectedIntent: 'farewell' },
    { text: 'cheerio my friend', expectedIntent: 'farewell' },
    { text: 'bye then everyone', expectedIntent: 'farewell' },
    { text: 'im off now', expectedIntent: 'farewell' },
    { text: 'bye bye my friend', expectedIntent: 'farewell' },
    { text: 'see ya later', expectedIntent: 'farewell' },
    { text: 'later my friend', expectedIntent: 'farewell' },
    { text: 'talk to you later buddy', expectedIntent: 'farewell' },
    { text: 'farewell my friend', expectedIntent: 'farewell' },
    { text: 'take care everyone', expectedIntent: 'farewell' },
    { text: 'see you soon', expectedIntent: 'farewell' },
    { text: 'catch you later friend', expectedIntent: 'farewell' },

    // Name examples
    { text: 'who are you exactly', expectedIntent: 'name' },
    { text: 'what is your name please', expectedIntent: 'name' },
    { text: 'what are you called now', expectedIntent: 'name' },
    { text: 'do you have a name', expectedIntent: 'name' },
    { text: 'may I ask your name', expectedIntent: 'name' },
    { text: 'can you tell me your name', expectedIntent: 'name' },
    { text: 'tell me your name please', expectedIntent: 'name' },
    { text: 'what should I call you', expectedIntent: 'name' },
    { text: 'how should I address you', expectedIntent: 'name' },
    { text: 'your name please', expectedIntent: 'name' },
    { text: 'who am I talking to', expectedIntent: 'name' },
    { text: 'what do people call you', expectedIntent: 'name' },
    { text: 'name of yours', expectedIntent: 'name' },
    { text: 'may I know your name', expectedIntent: 'name' },
    { text: 'what is your name then', expectedIntent: 'name' },

    // Age examples
    { text: 'how old are you today', expectedIntent: 'age' },
    { text: 'what is your age now', expectedIntent: 'age' },
    { text: 'can you tell me your age', expectedIntent: 'age' },
    { text: 'may I ask your age', expectedIntent: 'age' },
    { text: 'how many years old are you', expectedIntent: 'age' },
    { text: 'what age are you exactly', expectedIntent: 'age' },
    { text: 'tell me your age please', expectedIntent: 'age' },
    { text: 'could you tell me your age', expectedIntent: 'age' },
    { text: 'would you mind telling me how old you are', expectedIntent: 'age' },
    { text: 'I was wondering how old you are', expectedIntent: 'age' },
    { text: 'your age please', expectedIntent: 'age' },
    { text: 'how old', expectedIntent: 'age' },
    { text: 'how old might you be', expectedIntent: 'age' },
    { text: 'how many years have you', expectedIntent: 'age' },
    { text: 'your age now', expectedIntent: 'age' },
];

const testDatasetErroneous = [
    { text: 'what time is it', expectedIntent: null },
    { text: 'tell me a joke', expectedIntent: null },
    { text: 'how is the weather today', expectedIntent: null },
    { text: 'can you recommend a movie', expectedIntent: null },
    { text: 'i like pizza', expectedIntent: null },
    { text: 'my favorite color is blue', expectedIntent: null },
    { text: 'do you like music', expectedIntent: null },
    { text: 'what is 5 plus 7', expectedIntent: null },
    { text: 'show me a picture of a cat', expectedIntent: null },
    { text: 'i am learning javascript', expectedIntent: null },
    { text: 'can you help me with homework', expectedIntent: null },
    { text: 'what is the capital of France', expectedIntent: null },
    { text: 'how do airplanes fly', expectedIntent: null },
    { text: 'i enjoy reading books', expectedIntent: null },
    { text: 'do you play games', expectedIntent: null },
    { text: 'what is the meaning of life', expectedIntent: null },
    { text: 'how far is the moon', expectedIntent: null },
    { text: 'i love programming', expectedIntent: null },
    { text: 'do you know about AI', expectedIntent: null },
    { text: 'what is your favorite food', expectedIntent: null },
    { text: 'tell me a story', expectedIntent: null },
    { text: 'how do you bake a cake', expectedIntent: null },
    { text: 'can you solve this puzzle', expectedIntent: null },
    { text: 'i have a dog', expectedIntent: null },
    { text: 'my phone battery is low', expectedIntent: null },
    { text: 'what is the tallest mountain', expectedIntent: null },
    { text: 'i like to paint', expectedIntent: null },
    { text: 'do you enjoy sports', expectedIntent: null },
    { text: 'what is the speed of light', expectedIntent: null },
    { text: 'can you recommend a song', expectedIntent: null },
    { text: 'i like swimming', expectedIntent: null },
    { text: 'what is your favorite movie', expectedIntent: null },
    { text: 'how do plants grow', expectedIntent: null },
    { text: 'i enjoy hiking', expectedIntent: null },
    { text: 'can you explain photosynthesis', expectedIntent: null },
    { text: 'tell me about space', expectedIntent: null },
    { text: 'i love ice cream', expectedIntent: null },
    { text: 'what is quantum physics', expectedIntent: null },
    { text: 'do you like traveling', expectedIntent: null },
    { text: 'i need help with math', expectedIntent: null },
    { text: 'what is your favorite color', expectedIntent: null },
    { text: 'how do you tie a tie', expectedIntent: null },
    { text: 'tell me about history', expectedIntent: null },
    { text: 'i enjoy drawing', expectedIntent: null },
    { text: 'what is the largest ocean', expectedIntent: null },
    { text: 'do you know any fun facts', expectedIntent: null },
    { text: 'i like to dance', expectedIntent: null },
    { text: 'how does a car engine work', expectedIntent: null },
    { text: 'can you play music', expectedIntent: null },
    { text: 'i enjoy photography', expectedIntent: null },
    { text: 'what is the population of Japan', expectedIntent: null },
    { text: 'how do computers work', expectedIntent: null }
];

module.exports = {
    testDatasetExact,
    testDatasetFuzzy,
    testDatasetBoundary,
    testDatasetErroneous
};

